<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lockss-config [
<!ELEMENT lockss-config (if|property)*>
<!ELEMENT property (property|list|value|if)*>
<!ELEMENT list (value)+>
<!ELEMENT value (#PCDATA)>
<!ELEMENT test EMPTY>
<!ELEMENT and (and|or|not|test)*>
<!ELEMENT or (and|or|not|test)*>
<!ELEMENT not (and|or|not|test)*>
<!ELEMENT if (and|or|not|then|else|test|property)*>
<!ELEMENT then (if|property)*>
<!ELEMENT else (if|property)*>
<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST property value CDATA #IMPLIED>
<!ATTLIST test hostname CDATA #IMPLIED>
<!ATTLIST test group CDATA #IMPLIED>
<!ATTLIST test daemonVersionMin CDATA #IMPLIED>
<!ATTLIST test daemonVersionMax CDATA #IMPLIED>
<!ATTLIST test daemonVersion CDATA #IMPLIED>
<!ATTLIST test platformVersionMin CDATA #IMPLIED>
<!ATTLIST test platformVersionMax CDATA #IMPLIED>
<!ATTLIST test platformVersion CDATA #IMPLIED>
<!ATTLIST test platformName CDATA #IMPLIED>
<!ATTLIST if hostname CDATA #IMPLIED>
<!ATTLIST if group CDATA #IMPLIED>
<!ATTLIST if daemonVersionMin CDATA #IMPLIED>
<!ATTLIST if daemonVersionMax CDATA #IMPLIED>
<!ATTLIST if daemonVersion CDATA #IMPLIED>
<!ATTLIST if platformVersionMin CDATA #IMPLIED>
<!ATTLIST if platformVersionMax CDATA #IMPLIED>
<!ATTLIST if platformVersion CDATA #IMPLIED>
<!ATTLIST if platformName CDATA #IMPLIED>
<!ATTLIST list append CDATA #IMPLIED>
]>

<!-- Aug 1, 2017 9:59:58 AM -->

<lockss-config>

 <property name="org.lockss.titleSet">

  <property name="Pensoft Publishers">
   <property name="name" value="All Pensoft Publishers AUs" />
   <property name="class" value="xpath" />
   <property name="xpath" value='[attributes/publisher="Pensoft Publishers"]' />
  </property>

 </property>

 <property name="org.lockss.title">

  <property name="PensoftOaiPluginBiodiversityDataJournal2013">
   <property name="attributes.publisher" value="Pensoft Publishers" />
   <property name="journalTitle" value="Biodiversity Data Journal" />
   <property name="issn" value="1314-2836" />
   <property name="eissn" value="1314-2828" />
   <property name="issnl" value="1314-2836" />
   <property name="type" value="journal" />
   <property name="title" value="Biodiversity Data Journal Volume 2013" />
   <property name="plugin" value="org.lockss.plugin.pensoft.oai.PensoftOaiPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://bdj.pensoft.net/" />
   </property>
   <property name="param.2">
    <property name="key" value="au_oai_date" />
    <property name="value" value="2013" />
   </property>
   <property name="param.3">
    <property name="key" value="au_oai_set" />
    <property name="value" value="bdj" />
   </property>
   <property name="attributes.year" value="2013" />
   <property name="attributes.volume" value="1" />
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="PensoftOaiPluginBiodiversityDataJournal2014">
   <property name="attributes.publisher" value="Pensoft Publishers" />
   <property name="journalTitle" value="Biodiversity Data Journal" />
   <property name="issn" value="1314-2836" />
   <property name="eissn" value="1314-2828" />
   <property name="issnl" value="1314-2836" />
   <property name="type" value="journal" />
   <property name="title" value="Biodiversity Data Journal Volume 2014" />
   <property name="plugin" value="org.lockss.plugin.pensoft.oai.PensoftOaiPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://bdj.pensoft.net/" />
   </property>
   <property name="param.2">
    <property name="key" value="au_oai_date" />
    <property name="value" value="2014" />
   </property>
   <property name="param.3">
    <property name="key" value="au_oai_set" />
    <property name="value" value="bdj" />
   </property>
   <property name="attributes.year" value="2014" />
   <property name="attributes.volume" value="2" />
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="PensoftOaiPluginBiodiversityDataJournal2015">
   <property name="attributes.publisher" value="Pensoft Publishers" />
   <property name="journalTitle" value="Biodiversity Data Journal" />
   <property name="issn" value="1314-2836" />
   <property name="eissn" value="1314-2828" />
   <property name="issnl" value="1314-2836" />
   <property name="type" value="journal" />
   <property name="title" value="Biodiversity Data Journal Volume 2015" />
   <property name="plugin" value="org.lockss.plugin.pensoft.oai.PensoftOaiPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://bdj.pensoft.net/" />
   </property>
   <property name="param.2">
    <property name="key" value="au_oai_date" />
    <property name="value" value="2015" />
   </property>
   <property name="param.3">
    <property name="key" value="au_oai_set" />
    <property name="value" value="bdj" />
   </property>
   <property name="attributes.year" value="2015" />
   <property name="attributes.volume" value="3" />
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="PensoftOaiPluginBiodiversityDataJournal2016">
   <property name="attributes.publisher" value="Pensoft Publishers" />
   <property name="journalTitle" value="Biodiversity Data Journal" />
   <property name="issn" value="1314-2836" />
   <property name="eissn" value="1314-2828" />
   <property name="issnl" value="1314-2836" />
   <property name="type" value="journal" />
   <property name="title" value="Biodiversity Data Journal Volume 2016" />
   <property name="plugin" value="org.lockss.plugin.pensoft.oai.PensoftOaiPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://bdj.pensoft.net/" />
   </property>
   <property name="param.2">
    <property name="key" value="au_oai_date" />
    <property name="value" value="2016" />
   </property>
   <property name="param.3">
    <property name="key" value="au_oai_set" />
    <property name="value" value="bdj" />
   </property>
   <property name="attributes.year" value="2016" />
   <property name="attributes.volume" value="4" />
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="PensoftOaiPluginBioRisk2013">
   <property name="attributes.publisher" value="Pensoft Publishers" />
   <property name="journalTitle" value="BioRisk" />
   <property name="issn" value="1313-2644" />
   <property name="eissn" value="1313-2652" />
   <property name="issnl" value="1313-2644" />
   <property name="type" value="journal" />
   <property name="title" value="BioRisk Volume 2013" />
   <property name="plugin" value="org.lockss.plugin.pensoft.oai.PensoftOaiPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://biorisk.pensoft.net/" />
   </property>
   <property name="param.2">
    <property name="key" value="au_oai_date" />
    <property name="value" value="2013" />
   </property>
   <property name="param.3">
    <property name="key" value="au_oai_set" />
    <property name="value" value="biorisk" />
   </property>
   <property name="attributes.year" value="2013" />
   <property name="attributes.volume" value="8" />
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="PensoftOaiPluginBioRisk2014">
   <property name="attributes.publisher" value="Pensoft Publishers" />
   <property name="journalTitle" value="BioRisk" />
   <property name="issn" value="1313-2644" />
   <property name="eissn" value="1313-2652" />
   <property name="issnl" value="1313-2644" />
   <property name="type" value="journal" />
   <property name="title" value="BioRisk Volume 2014" />
   <property name="plugin" value="org.lockss.plugin.pensoft.oai.PensoftOaiPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://biorisk.pensoft.net/" />
   </property>
   <property name="param.2">
    <property name="key" value="au_oai_date" />
    <property name="value" value="2014" />
   </property>
   <property name="param.3">
    <property name="key" value="au_oai_set" />
    <property name="value" value="biorisk" />
   </property>
   <property name="attributes.year" value="2014" />
   <property name="attributes.volume" value="9" />
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="PensoftOaiPluginBioRisk2015">
   <property name="attributes.publisher" value="Pensoft Publishers" />
   <property name="journalTitle" value="BioRisk" />
   <property name="issn" value="1313-2644" />
   <property name="eissn" value="1313-2652" />
   <property name="issnl" value="1313-2644" />
   <property name="type" value="journal" />
   <property name="title" value="BioRisk Volume 2015" />
   <property name="plugin" value="org.lockss.plugin.pensoft.oai.PensoftOaiPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://biorisk.pensoft.net/" />
   </property>
   <property name="param.2">
    <property name="key" value="au_oai_date" />
    <property name="value" value="2015" />
   </property>
   <property name="param.3">
    <property name="key" value="au_oai_set" />
    <property name="value" value="biorisk" />
   </property>
   <property name="attributes.year" value="2015" />
   <property name="attributes.volume" value="10" />
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="PensoftOaiPluginBioRisk2016">
   <property name="attributes.publisher" value="Pensoft Publishers" />
   <property name="journalTitle" value="BioRisk" />
   <property name="issn" value="1313-2644" />
   <property name="eissn" value="1313-2652" />
   <property name="issnl" value="1313-2644" />
   <property name="type" value="journal" />
   <property name="title" value="BioRisk Volume 2016" />
   <property name="plugin" value="org.lockss.plugin.pensoft.oai.PensoftOaiPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://biorisk.pensoft.net/" />
   </property>
   <property name="param.2">
    <property name="key" value="au_oai_date" />
    <property name="value" value="2016" />
   </property>
   <property name="param.3">
    <property name="key" value="au_oai_set" />
    <property name="value" value="biorisk" />
   </property>
   <property name="attributes.year" value="2016" />
   <property name="attributes.volume" value="11" />
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="PensoftOaiPluginComparativeCytogenetics2013">
   <property name="attributes.publisher" value="Pensoft Publishers" />
   <property name="journalTitle" value="Comparative Cytogenetics" />
   <property name="issn" value="1993-0771" />
   <property name="eissn" value="1993-078X" />
   <property name="issnl" value="1993-0771" />
   <property name="type" value="journal" />
   <property name="title" value="Comparative Cytogenetics Volume 2013" />
   <property name="plugin" value="org.lockss.plugin.pensoft.oai.PensoftOaiPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://compcytogen.pensoft.net/" />
   </property>
   <property name="param.2">
    <property name="key" value="au_oai_date" />
    <property name="value" value="2013" />
   </property>
   <property name="param.3">
    <property name="key" value="au_oai_set" />
    <property name="value" value="compcytogen" />
   </property>
   <property name="attributes.year" value="2013" />
   <property name="attributes.volume" value="7" />
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="PensoftOaiPluginComparativeCytogenetics2014">
   <property name="attributes.publisher" value="Pensoft Publishers" />
   <property name="journalTitle" value="Comparative Cytogenetics" />
   <property name="issn" value="1993-0771" />
   <property name="eissn" value="1993-078X" />
   <property name="issnl" value="1993-0771" />
   <property name="type" value="journal" />
   <property name="title" value="Comparative Cytogenetics Volume 2014" />
   <property name="plugin" value="org.lockss.plugin.pensoft.oai.PensoftOaiPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://compcytogen.pensoft.net/" />
   </property>
   <property name="param.2">
    <property name="key" value="au_oai_date" />
    <property name="value" value="2014" />
   </property>
   <property name="param.3">
    <property name="key" value="au_oai_set" />
    <property name="value" value="compcytogen" />
   </property>
   <property name="attributes.year" value="2014" />
   <property name="attributes.volume" value="8" />
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="PensoftOaiPluginComparativeCytogenetics2015">
   <property name="attributes.publisher" value="Pensoft Publishers" />
   <property name="journalTitle" value="Comparative Cytogenetics" />
   <property name="issn" value="1993-0771" />
   <property name="eissn" value="1993-078X" />
   <property name="issnl" value="1993-0771" />
   <property name="type" value="journal" />
   <property name="title" value="Comparative Cytogenetics Volume 2015" />
   <property name="plugin" value="org.lockss.plugin.pensoft.oai.PensoftOaiPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://compcytogen.pensoft.net/" />
   </property>
   <property name="param.2">
    <property name="key" value="au_oai_date" />
    <property name="value" value="2015" />
   </property>
   <property name="param.3">
    <property name="key" value="au_oai_set" />
    <property name="value" value="compcytogen" />
   </property>
   <property name="attributes.year" value="2015" />
   <property name="attributes.volume" value="9" />
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="PensoftOaiPluginComparativeCytogenetics2016">
   <property name="attributes.publisher" value="Pensoft Publishers" />
   <property name="journalTitle" value="Comparative Cytogenetics" />
   <property name="issn" value="1993-0771" />
   <property name="eissn" value="1993-078X" />
   <property name="issnl" value="1993-0771" />
   <property name="type" value="journal" />
   <property name="title" value="Comparative Cytogenetics Volume 2016" />
   <property name="plugin" value="org.lockss.plugin.pensoft.oai.PensoftOaiPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://compcytogen.pensoft.net/" />
   </property>
   <property name="param.2">
    <property name="key" value="au_oai_date" />
    <property name="value" value="2016" />
   </property>
   <property name="param.3">
    <property name="key" value="au_oai_set" />
    <property name="value" value="compcytogen" />
   </property>
   <property name="attributes.year" value="2016" />
   <property name="attributes.volume" value="10" />
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="PensoftOaiPluginDeutscheEntomologischeZeitschrift2014">
   <property name="attributes.publisher" value="Pensoft Publishers" />
   <property name="journalTitle" value="Deutsche Entomologische Zeitschrift" />
   <property name="issn" value="1435-1951" />
   <property name="eissn" value="1860-1324" />
   <property name="issnl" value="1435-1951" />
   <property name="type" value="journal" />
   <property name="title" value="Deutsche Entomologische Zeitschrift Volume 2014" />
   <property name="plugin" value="org.lockss.plugin.pensoft.oai.PensoftOaiPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dez.pensoft.net/" />
   </property>
   <property name="param.2">
    <property name="key" value="au_oai_date" />
    <property name="value" value="2014" />
   </property>
   <property name="param.3">
    <property name="key" value="au_oai_set" />
    <property name="value" value="dez" />
   </property>
   <property name="attributes.year" value="2014" />
   <property name="attributes.volume" value="61" />
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="PensoftOaiPluginDeutscheEntomologischeZeitschrift2015">
   <property name="attributes.publisher" value="Pensoft Publishers" />
   <property name="journalTitle" value="Deutsche Entomologische Zeitschrift" />
   <property name="issn" value="1435-1951" />
   <property name="eissn" value="1860-1324" />
   <property name="issnl" value="1435-1951" />
   <property name="type" value="journal" />
   <property name="title" value="Deutsche Entomologische Zeitschrift Volume 2015" />
   <property name="plugin" value="org.lockss.plugin.pensoft.oai.PensoftOaiPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dez.pensoft.net/" />
   </property>
   <property name="param.2">
    <property name="key" value="au_oai_date" />
    <property name="value" value="2015" />
   </property>
   <property name="param.3">
    <property name="key" value="au_oai_set" />
    <property name="value" value="dez" />
   </property>
   <property name="attributes.year" value="2015" />
   <property name="attributes.volume" value="62" />
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="PensoftOaiPluginDeutscheEntomologischeZeitschrift2016">
   <property name="attributes.publisher" value="Pensoft Publishers" />
   <property name="journalTitle" value="Deutsche Entomologische Zeitschrift" />
   <property name="issn" value="1435-1951" />
   <property name="eissn" value="1860-1324" />
   <property name="issnl" value="1435-1951" />
   <property name="type" value="journal" />
   <property name="title" value="Deutsche Entomologische Zeitschrift Volume 2016" />
   <property name="plugin" value="org.lockss.plugin.pensoft.oai.PensoftOaiPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://dez.pensoft.net/" />
   </property>
   <property name="param.2">
    <property name="key" value="au_oai_date" />
    <property name="value" value="2016" />
   </property>
   <property name="param.3">
    <property name="key" value="au_oai_set" />
    <property name="value" value="dez" />
   </property>
   <property name="attributes.year" value="2016" />
   <property name="attributes.volume" value="63" />
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="PensoftOaiPluginJournalofHymenopteraResearch2013">
   <property name="attributes.publisher" value="Pensoft Publishers" />
   <property name="journalTitle" value="Journal of Hymenoptera Research" />
   <property name="issn" value="1070-9428" />
   <property name="eissn" value="1314-2607" />
   <property name="issnl" value="1070-9428" />
   <property name="type" value="journal" />
   <property name="title" value="Journal of Hymenoptera Research Volume 2013" />
   <property name="plugin" value="org.lockss.plugin.pensoft.oai.PensoftOaiPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://jhr.pensoft.net/" />
   </property>
   <property name="param.2">
    <property name="key" value="au_oai_date" />
    <property name="value" value="2013" />
   </property>
   <property name="param.3">
    <property name="key" value="au_oai_set" />
    <property name="value" value="jhr" />
   </property>
   <property name="attributes.year" value="2013" />
   <property name="attributes.volume" value="30-35" />
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="PensoftOaiPluginJournalofHymenopteraResearch2014">
   <property name="attributes.publisher" value="Pensoft Publishers" />
   <property name="journalTitle" value="Journal of Hymenoptera Research" />
   <property name="issn" value="1070-9428" />
   <property name="eissn" value="1314-2607" />
   <property name="issnl" value="1070-9428" />
   <property name="type" value="journal" />
   <property name="title" value="Journal of Hymenoptera Research Volume 2014" />
   <property name="plugin" value="org.lockss.plugin.pensoft.oai.PensoftOaiPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://jhr.pensoft.net/" />
   </property>
   <property name="param.2">
    <property name="key" value="au_oai_date" />
    <property name="value" value="2014" />
   </property>
   <property name="param.3">
    <property name="key" value="au_oai_set" />
    <property name="value" value="jhr" />
   </property>
   <property name="attributes.year" value="2014" />
   <property name="attributes.volume" value="36-41" />
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="PensoftOaiPluginJournalofHymenopteraResearch2015">
   <property name="attributes.publisher" value="Pensoft Publishers" />
   <property name="journalTitle" value="Journal of Hymenoptera Research" />
   <property name="issn" value="1070-9428" />
   <property name="eissn" value="1314-2607" />
   <property name="issnl" value="1070-9428" />
   <property name="type" value="journal" />
   <property name="title" value="Journal of Hymenoptera Research Volume 2015" />
   <property name="plugin" value="org.lockss.plugin.pensoft.oai.PensoftOaiPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://jhr.pensoft.net/" />
   </property>
   <property name="param.2">
    <property name="key" value="au_oai_date" />
    <property name="value" value="2015" />
   </property>
   <property name="param.3">
    <property name="key" value="au_oai_set" />
    <property name="value" value="jhr" />
   </property>
   <property name="attributes.year" value="2015" />
   <property name="attributes.volume" value="42-47" />
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="PensoftOaiPluginJournalofHymenopteraResearch2016">
   <property name="attributes.publisher" value="Pensoft Publishers" />
   <property name="journalTitle" value="Journal of Hymenoptera Research" />
   <property name="issn" value="1070-9428" />
   <property name="eissn" value="1314-2607" />
   <property name="issnl" value="1070-9428" />
   <property name="type" value="journal" />
   <property name="title" value="Journal of Hymenoptera Research Volume 2016" />
   <property name="plugin" value="org.lockss.plugin.pensoft.oai.PensoftOaiPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://jhr.pensoft.net/" />
   </property>
   <property name="param.2">
    <property name="key" value="au_oai_date" />
    <property name="value" value="2016" />
   </property>
   <property name="param.3">
    <property name="key" value="au_oai_set" />
    <property name="value" value="jhr" />
   </property>
   <property name="attributes.year" value="2016" />
   <property name="attributes.volume" value="48-53" />
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="PensoftOaiPluginMycoKeys2013">
   <property name="attributes.publisher" value="Pensoft Publishers" />
   <property name="journalTitle" value="MycoKeys" />
   <property name="issn" value="1314-4057" />
   <property name="eissn" value="1314-4049" />
   <property name="issnl" value="1314-4057" />
   <property name="type" value="journal" />
   <property name="title" value="MycoKeys Volume 2013" />
   <property name="plugin" value="org.lockss.plugin.pensoft.oai.PensoftOaiPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://mycokeys.pensoft.net/" />
   </property>
   <property name="param.2">
    <property name="key" value="au_oai_date" />
    <property name="value" value="2013" />
   </property>
   <property name="param.3">
    <property name="key" value="au_oai_set" />
    <property name="value" value="mycokeys" />
   </property>
   <property name="attributes.year" value="2013" />
   <property name="attributes.volume" value="6-7" />
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="PensoftOaiPluginMycoKeys2014">
   <property name="attributes.publisher" value="Pensoft Publishers" />
   <property name="journalTitle" value="MycoKeys" />
   <property name="issn" value="1314-4057" />
   <property name="eissn" value="1314-4049" />
   <property name="issnl" value="1314-4057" />
   <property name="type" value="journal" />
   <property name="title" value="MycoKeys Volume 2014" />
   <property name="plugin" value="org.lockss.plugin.pensoft.oai.PensoftOaiPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://mycokeys.pensoft.net/" />
   </property>
   <property name="param.2">
    <property name="key" value="au_oai_date" />
    <property name="value" value="2014" />
   </property>
   <property name="param.3">
    <property name="key" value="au_oai_set" />
    <property name="value" value="mycokeys" />
   </property>
   <property name="attributes.year" value="2014" />
   <property name="attributes.volume" value="8" />
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="PensoftOaiPluginMycoKeys2015">
   <property name="attributes.publisher" value="Pensoft Publishers" />
   <property name="journalTitle" value="MycoKeys" />
   <property name="issn" value="1314-4057" />
   <property name="eissn" value="1314-4049" />
   <property name="issnl" value="1314-4057" />
   <property name="type" value="journal" />
   <property name="title" value="MycoKeys Volume 2015" />
   <property name="plugin" value="org.lockss.plugin.pensoft.oai.PensoftOaiPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://mycokeys.pensoft.net/" />
   </property>
   <property name="param.2">
    <property name="key" value="au_oai_date" />
    <property name="value" value="2015" />
   </property>
   <property name="param.3">
    <property name="key" value="au_oai_set" />
    <property name="value" value="mycokeys" />
   </property>
   <property name="attributes.year" value="2015" />
   <property name="attributes.volume" value="9-11" />
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="PensoftOaiPluginMycoKeys2016">
   <property name="attributes.publisher" value="Pensoft Publishers" />
   <property name="journalTitle" value="MycoKeys" />
   <property name="issn" value="1314-4057" />
   <property name="eissn" value="1314-4049" />
   <property name="issnl" value="1314-4057" />
   <property name="type" value="journal" />
   <property name="title" value="MycoKeys Volume 2016" />
   <property name="plugin" value="org.lockss.plugin.pensoft.oai.PensoftOaiPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://mycokeys.pensoft.net/" />
   </property>
   <property name="param.2">
    <property name="key" value="au_oai_date" />
    <property name="value" value="2016" />
   </property>
   <property name="param.3">
    <property name="key" value="au_oai_set" />
    <property name="value" value="mycokeys" />
   </property>
   <property name="attributes.year" value="2016" />
   <property name="attributes.volume" value="12-18" />
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="PensoftOaiPluginNatureConservation2013">
   <property name="attributes.publisher" value="Pensoft Publishers" />
   <property name="journalTitle" value="Nature Conservation" />
   <property name="eissn" value="1314-3301" />
   <property name="type" value="journal" />
   <property name="title" value="Nature Conservation Volume 2013" />
   <property name="plugin" value="org.lockss.plugin.pensoft.oai.PensoftOaiPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://natureconservation.pensoft.net/" />
   </property>
   <property name="param.2">
    <property name="key" value="au_oai_date" />
    <property name="value" value="2013" />
   </property>
   <property name="param.3">
    <property name="key" value="au_oai_set" />
    <property name="value" value="natureconservation" />
   </property>
   <property name="attributes.year" value="2013" />
   <property name="attributes.volume" value="4-6" />
   <property name="attributes.rights" value="openaccess" />
  </property>

  <property name="PensoftOaiPluginNatureConservation2014">
   <property name="attributes.publisher" value="Pensoft Publishers" />
   <property name="journalTitle" value="Nature Conservation" />
   <property name="eissn" value="1314-3301" />
   <property name="type" value="journal" />
   <property name="title" value="Nature Conservation Volume 2014" />
   <property name="plugin" value="org.lockss.plugin.pensoft.oai.PensoftOaiPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://natureconservation.pensoft.net/" />
   </property>
   <property name="param.2">
    <property name="key" value="au_oai_date" />
    <property name="value" value="2014" />
   </property>
   <property name="param.3">
    <property name="key" value="au_oai_set" />
    <property name="value" value="natureconservation" />
   </property>