<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lockss-config [
<!ELEMENT lockss-config (if|property)*>
<!ELEMENT property (property|list|value|if)*>
<!ELEMENT list (value)+>
<!ELEMENT value (#PCDATA)>
<!ELEMENT test EMPTY>
<!ELEMENT and (and|or|not|test)*>
<!ELEMENT or (and|or|not|test)*>
<!ELEMENT not (and|or|not|test)*>
<!ELEMENT if (and|or|not|then|else|test|property)*>
<!ELEMENT then (if|property)*>
<!ELEMENT else (if|property)*>
<!ATTLIST property name CDATA #REQUIRED>
<!ATTLIST property value CDATA #IMPLIED>
<!ATTLIST test hostname CDATA #IMPLIED>
<!ATTLIST test group CDATA #IMPLIED>
<!ATTLIST test daemonVersionMin CDATA #IMPLIED>
<!ATTLIST test daemonVersionMax CDATA #IMPLIED>
<!ATTLIST test daemonVersion CDATA #IMPLIED>
<!ATTLIST test platformVersionMin CDATA #IMPLIED>
<!ATTLIST test platformVersionMax CDATA #IMPLIED>
<!ATTLIST test platformVersion CDATA #IMPLIED>
<!ATTLIST test platformName CDATA #IMPLIED>
<!ATTLIST if hostname CDATA #IMPLIED>
<!ATTLIST if group CDATA #IMPLIED>
<!ATTLIST if daemonVersionMin CDATA #IMPLIED>
<!ATTLIST if daemonVersionMax CDATA #IMPLIED>
<!ATTLIST if daemonVersion CDATA #IMPLIED>
<!ATTLIST if platformVersionMin CDATA #IMPLIED>
<!ATTLIST if platformVersionMax CDATA #IMPLIED>
<!ATTLIST if platformVersion CDATA #IMPLIED>
<!ATTLIST if platformName CDATA #IMPLIED>
<!ATTLIST list append CDATA #IMPLIED>
]>

<!-- Mar 16, 2017 8:37:52 AM -->

<lockss-config>

 <property name="org.lockss.titleSet">

  <property name="Taylor &amp; Francis">
   <property name="name" value="All Taylor &amp; Francis AUs" />
   <property name="class" value="xpath" />
   <property name="xpath" value='[attributes/publisher="Taylor &amp; Francis"]' />
  </property>

 </property>

 <property name="org.lockss.title">

  <property name="TaylorAndFrancisPluginAfricaReview8">
   <property name="attributes.publisher" value="Taylor &amp; Francis" />
   <property name="journalTitle" value="Africa Review" />
   <property name="issn" value="0974-4053" />
   <property name="eissn" value="0974-4061" />
   <property name="issnl" value="0974-4053" />
   <property name="type" value="journal" />
   <property name="title" value="Africa Review Volume 8" />
   <property name="plugin" value="org.lockss.plugin.taylorandfrancis.TaylorAndFrancisPlugin" />
   <property name="param.1">
    <property name="key" value="base_url" />
    <property name="value" value="http://www.tandfonline.com/" />
   </property>
   <property name="param.2">
    <property name="key" value="journal_id" />
    <property name="value" value="rafr20" />
   </property>
   <property name="param.3">
    <property name="key" value="volume_name" />
    <property name="value" value="8" />
   </property>
   <property name="attributes.year" value="2016" />
  </property>

 </property>

</lockss-config>
